import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { Transaction, Summary } from '../types';
import { t, Lang } from './i18nService';

export const generateFinancialReport = (transactions: Transaction[], summary: Summary, healthScore: number, lang: Lang) => {
    const doc = new jsPDF() as any;
    const primaryColor = [255, 210, 31]; // Kasa Yellow

    // Header
    doc.setFillColor(0, 0, 0);
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('KASA FINANCIAL REPORT', 20, 25);
    
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(10);
    doc.text(`EXECUTIVE SUMMARY • ${new Date().toLocaleDateString()}`, 20, 32);

    // Health Score Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text(t('financialHealth', lang).toUpperCase(), 20, 55);
    
    doc.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.setLineWidth(1);
    doc.line(20, 58, 190, 58);

    doc.setFontSize(40);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text(healthScore.toString(), 20, 80);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('/ 100', 45, 80);
    doc.text(t('healthScoreDescription', lang), 20, 88);

    // Summary Metrics
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('PORTFOLIO MATRICS', 20, 105);
    
    const summaryData = [
        [t('totalIncome', lang), `TRY ${summary.total_income.toLocaleString()}`],
        [t('totalExpense', lang), `TRY ${summary.total_expense.toLocaleString()}`],
        [t('balance', lang), `TRY ${(summary.total_income - summary.total_expense).toLocaleString()}`]
    ];

    doc.autoTable({
        startY: 110,
        head: [['Metric', 'Value']],
        body: summaryData,
        theme: 'grid',
        headStyles: { fillColor: [30, 30, 30], textColor: [255, 255, 255] },
        styles: { fontSize: 10 }
    });

    // Recent Transactions
    doc.setFontSize(14);
    doc.text('RECENT SETTLEMENTS', 20, doc.lastAutoTable.finalY + 20);

    const transactionData = transactions.slice(0, 15).map(tr => [
        tr.date,
        tr.description,
        tr.category_name || 'N/A',
        tr.type === 'income' ? `+${tr.amount}` : `-${tr.amount}`
    ]);

    doc.autoTable({
        startY: doc.lastAutoTable.finalY + 25,
        head: [['Date', 'Description', 'Category', 'Amount']],
        body: transactionData,
        theme: 'striped',
        headStyles: { fillColor: [30, 30, 30] },
        styles: { fontSize: 9 }
    });

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('CONFIDENTIAL • GENERATED BY PERSONAL OS KASA ENGINE', 105, 285, { align: 'center' });
    }

    doc.save(`Kasa_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};
